import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const pw = require('/opt/node22/lib/node_modules/playwright');
const browser = await pw.chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 844, height: 390 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true, locale: 'tr-TR' });
const logs = [];
page.on('console', (m) => { if (m.type() === 'error') logs.push(m.text()); });
page.on('pageerror', (e) => logs.push('PAGEERROR ' + e.message));
await page.goto('http://localhost:5173/?demo=fresh', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.screenshot({ path: 'screenshots/tmp/ui-main.png' });
await page.click('text=Mağaza');
await page.waitForTimeout(800);
await page.screenshot({ path: 'screenshots/tmp/ui-shop.png' });
await page.click('.mhead .iconbtn');
await page.mouse.click(430, 220);
await page.waitForTimeout(500);
await page.click('text=Bakım');
await page.waitForTimeout(800);
await page.screenshot({ path: 'screenshots/tmp/ui-care.png' });
console.log(logs.slice(0, 20).join('\n') || 'no errors');
await browser.close();
